VERSES = {
    ["Cappadonna"] = {
        make_audio('/verses/cappadonna/cap tri1.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri2.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri3.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri4.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri5.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri6.mp3','stream'),
        make_audio('/verses/cappadonna/cap tri7.mp3','stream'),
        make_audio('/verses/cappadonna/cap jump1.mp3','stream'),
        make_audio('/verses/cappadonna/cap jump2.mp3','stream'),
        make_audio('/verses/cappadonna/cap jump3.mp3','stream'),
        make_audio('/verses/cappadonna/cap jump4.mp3','stream'),
        make_audio('/verses/cappadonna/cap jump5.mp3','stream')
    },
    ["Ghostface Killah"] = {
        make_audio('/verses/ghostface/gf chess1.mp3','stream'),
        make_audio('/verses/ghostface/gf chess2.mp3','stream'),
        make_audio('/verses/ghostface/gf chess3.mp3','stream'),
        make_audio('/verses/ghostface/gf chess4.mp3','stream'),
        make_audio('/verses/ghostface/gf chess5.mp3','stream'),
        make_audio('/verses/ghostface/gf chess6.mp3','stream'),
        make_audio('/verses/ghostface/gf chess7.mp3','stream'),
        make_audio('/verses/ghostface/gf tri1.mp3','stream'),
        make_audio('/verses/ghostface/gf tri2.mp3','stream'),
        make_audio('/verses/ghostface/gf tri3.mp3','stream'),
        make_audio('/verses/ghostface/gf tri4.mp3','stream'),
        make_audio('/verses/ghostface/gf tri5.mp3','stream'),
        make_audio('/verses/ghostface/gf tri6.mp3','stream'),
        make_audio('/verses/ghostface/gf tri7.mp3','stream'),
        make_audio('/verses/ghostface/gf gravel1.mp3','stream'),
        make_audio('/verses/ghostface/gf gravel2.mp3','stream'),
        make_audio('/verses/ghostface/gf gravel3.mp3','stream'),
        make_audio('/verses/ghostface/gf gravel4.mp3','stream'),
        make_audio('/verses/ghostface/gf gravel5.mp3','stream'),
        make_audio('/verses/ghostface/gf jump1.mp3','stream'),
        make_audio('/verses/ghostface/gf jump2.mp3','stream'),
        make_audio('/verses/ghostface/gf jump3.mp3','stream'),
        make_audio('/verses/ghostface/gf jump4.mp3','stream'),
        make_audio('/verses/ghostface/gf jump5.mp3','stream'),
        make_audio('/verses/ghostface/gf neck1.mp3','stream'),
        make_audio('/verses/ghostface/gf neck2.mp3','stream'),
        make_audio('/verses/ghostface/gf neck3.mp3','stream'),
        make_audio('/verses/ghostface/gf neck4.mp3','stream'),
        make_audio('/verses/ghostface/gf neck5.mp3','stream')
    },
    ["GZA"] = {
        make_audio('/verses/gza/gza re1.mp3','stream'),
        make_audio('/verses/gza/gza re2.mp3','stream'),
        make_audio('/verses/gza/gza re3.mp3','stream'),
        make_audio('/verses/gza/gza re4.mp3','stream'),
        make_audio('/verses/gza/gza re5.mp3','stream'),
        make_audio('/verses/gza/gza re6.mp3','stream'),
        make_audio('/verses/gza/gza re7.mp3','stream'),
        make_audio('/verses/gza/gza re8.mp3','stream'),
        make_audio('/verses/gza/gza tri1.mp3','stream'),
        make_audio('/verses/gza/gza tri2.mp3','stream'),
        make_audio('/verses/gza/gza tri3.mp3','stream'),
        make_audio('/verses/gza/gza jump1.mp3','stream'),
        make_audio('/verses/gza/gza jump2.mp3','stream'),
        make_audio('/verses/gza/gza jump3.mp3','stream'),
        make_audio('/verses/gza/gza jump4.mp3','stream'),
        make_audio('/verses/gza/gza neck1.mp3','stream'),
        make_audio('/verses/gza/gza neck2.mp3','stream'),
        make_audio('/verses/gza/gza neck3.mp3','stream'),
        make_audio('/verses/gza/gza neck4.mp3','stream'),
        make_audio('/verses/gza/gza neck5.mp3','stream'),
        make_audio('/verses/gza/gza neck6.mp3','stream'),
        make_audio('/verses/gza/gza neck7.mp3','stream'),
        make_audio('/verses/gza/gza neck8.mp3','stream')
    },
    ["Inspectah Deck"] = {
        make_audio('/verses/inspectah_deck/deck tri1.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri2.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri3.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri4.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri5.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri6.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri7.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri8.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck tri9.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess1.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess2.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess3.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess4.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess5.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck chess6.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck jump1.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck jump2.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck neck1.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck neck2.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck neck3.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck neck4.mp3','stream'),
        make_audio('/verses/inspectah_deck/deck neck5.mp3','stream')
    },
    ["Masta Killa"] = {
        make_audio('/verses/masta_killa/mk tri1.mp3','stream'),
        make_audio('/verses/masta_killa/mk tri2.mp3','stream'),
        make_audio('/verses/masta_killa/mk tri3.mp3','stream'),
        make_audio('/verses/masta_killa/mk tri4.mp3','stream'),
        make_audio('/verses/masta_killa/mk tri5.mp3','stream'),
        make_audio('/verses/masta_killa/mk tri6.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess1.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess2.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess3.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess4.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess5.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess6.mp3','stream'),
        make_audio('/verses/masta_killa/mk chess7.mp3','stream'),
        make_audio('/verses/masta_killa/mk jump1.mp3','stream'),
        make_audio('/verses/masta_killa/mk jump2.mp3','stream'),
        make_audio('/verses/masta_killa/mk jump3.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob1.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob2.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob3.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob4.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob5.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob6.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob7.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob8.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob9.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob10.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob11.mp3','stream'),
        make_audio('/verses/masta_killa/mk ob12.mp3','stream')
    },
    ["Method Man"] = {
        make_audio('/verses/method_man/meth tri1.mp3','stream'),
        make_audio('/verses/method_man/meth tri2.mp3','stream'),
        make_audio('/verses/method_man/meth tri3.mp3','stream'),
        make_audio('/verses/method_man/meth tri4.mp3','stream'),
        make_audio('/verses/method_man/meth tri5.mp3','stream'),
        make_audio('/verses/method_man/meth tri6.mp3','stream'),
        make_audio('/verses/method_man/meth tri7.mp3','stream'),
        make_audio('/verses/method_man/meth tri8.mp3','stream'),
        make_audio('/verses/method_man/meth re1.mp3','stream'),
        make_audio('/verses/method_man/meth re2.mp3','stream'),
        make_audio('/verses/method_man/meth re3.mp3','stream'),
        make_audio('/verses/method_man/meth re4.mp3','stream'),
        make_audio('/verses/method_man/meth re5.mp3','stream'),
        make_audio('/verses/method_man/meth re6.mp3','stream'),
        make_audio('/verses/method_man/meth re7.mp3','stream'),
        make_audio('/verses/method_man/meth gravel1.mp3','stream'),
        make_audio('/verses/method_man/meth gravel2.mp3','stream'),
        make_audio('/verses/method_man/meth gravel3.mp3','stream'),
        make_audio('/verses/method_man/meth gravel4.mp3','stream'),
        make_audio('/verses/method_man/meth gravel5.mp3','stream'),
        make_audio('/verses/method_man/meth gravel6.mp3','stream'),
        make_audio('/verses/method_man/meth gravel7.mp3','stream'),
        make_audio('/verses/method_man/meth gravel8.mp3','stream'),
        make_audio('/verses/method_man/meth gravel9.mp3','stream'),
        make_audio('/verses/method_man/meth gravel10.mp3','stream'),
        make_audio('/verses/method_man/meth gravel11.mp3','stream'),
        make_audio('/verses/method_man/meth jump1.mp3','stream'),
        make_audio('/verses/method_man/meth jump2.mp3','stream'),
        make_audio('/verses/method_man/meth jump3.mp3','stream'),
        make_audio('/verses/method_man/meth jump4.mp3','stream'),
        make_audio('/verses/method_man/meth jump5.mp3','stream'),
        make_audio('/verses/method_man/meth jump6.mp3','stream'),
        make_audio('/verses/method_man/meth neck1.mp3','stream'),
        make_audio('/verses/method_man/meth neck2.mp3','stream'),
        make_audio('/verses/method_man/meth neck3.mp3','stream'),
        make_audio('/verses/method_man/meth neck4.mp3','stream'),
        make_audio('/verses/method_man/meth neck5.mp3','stream'),
        make_audio('/verses/method_man/meth neck6.mp3','stream'),
        make_audio('/verses/method_man/meth shame1.mp3','stream'),
        make_audio('/verses/method_man/meth shame2.mp3','stream'),
        make_audio('/verses/method_man/meth shame3.mp3','stream'),
        make_audio('/verses/method_man/meth shame4.mp3','stream')
    },
    ["Ol' Dirty Bastard"] = {
        make_audio('/verses/odb/odb chess1.mp3','stream'),
        make_audio('/verses/odb/odb chess2.mp3','stream'),
        make_audio('/verses/odb/odb chess3.mp3','stream'),
        make_audio('/verses/odb/odb chess4.mp3','stream'),
        make_audio('/verses/odb/odb chess5.mp3','stream'),
        make_audio('/verses/odb/odb chess6.mp3','stream'),
        make_audio('/verses/odb/odb chess7.mp3','stream'),
        make_audio('/verses/odb/odb chess8.mp3','stream'),
        make_audio('/verses/odb/odb chess9.mp3','stream'),
        make_audio('/verses/odb/odb chess10.mp3','stream'),
        make_audio('/verses/odb/odb re1.mp3','stream'),
        make_audio('/verses/odb/odb neck1.mp3','stream'),
        make_audio('/verses/odb/odb neck2.mp3','stream'),
        make_audio('/verses/odb/odb neck3.mp3','stream'),
        make_audio('/verses/odb/odb neck4.mp3','stream'),
        make_audio('/verses/odb/odb shame1.mp3','stream'),
        make_audio('/verses/odb/odb shame2.mp3','stream'),
        make_audio('/verses/odb/odb shame3.mp3','stream'),
        make_audio('/verses/odb/odb shame4.mp3','stream'),
        make_audio('/verses/odb/odb shame5.mp3','stream'),
        make_audio('/verses/odb/odb shame6.mp3','stream'),
        make_audio('/verses/odb/odb shame7.mp3','stream'),
        make_audio('/verses/odb/odb shame8.mp3','stream'),
        make_audio('/verses/odb/odb shame9.mp3','stream')
    },
    ["Raekwon"] = {
        make_audio('/verses/raekwon/rae tri1.mp3','stream'),
        make_audio('/verses/raekwon/rae tri2.mp3','stream'),
        make_audio('/verses/raekwon/rae tri3.mp3','stream'),
        make_audio('/verses/raekwon/rae tri4.mp3','stream'),
        make_audio('/verses/raekwon/rae tri5.mp3','stream'),
        make_audio('/verses/raekwon/rae chess1.mp3','stream'),
        make_audio('/verses/raekwon/rae chess2.mp3','stream'),
        make_audio('/verses/raekwon/rae chess3.mp3','stream'),
        make_audio('/verses/raekwon/rae chess4.mp3','stream'),
        make_audio('/verses/raekwon/rae chess5.mp3','stream'),
        make_audio('/verses/raekwon/rae chess6.mp3','stream'),
        make_audio('/verses/raekwon/rae jump1.mp3','stream'),
        make_audio('/verses/raekwon/rae jump2.mp3','stream'),
        make_audio('/verses/raekwon/rae jump3.mp3','stream'),
        make_audio('/verses/raekwon/rae jump4.mp3','stream'),
        make_audio('/verses/raekwon/rae jump5.mp3','stream'),           
        make_audio('/verses/raekwon/rae neck1.mp3','stream'),
        make_audio('/verses/raekwon/rae neck2.mp3','stream'),
        make_audio('/verses/raekwon/rae neck3.mp3','stream'),
        make_audio('/verses/raekwon/rae neck4.mp3','stream'),
        make_audio('/verses/raekwon/rae neck5.mp3','stream'),
        make_audio('/verses/raekwon/rae shame1.mp3','stream'),
        make_audio('/verses/raekwon/rae shame2.mp3','stream'),
        make_audio('/verses/raekwon/rae shame3.mp3','stream')
    },
    ["RZA"] = {
        make_audio('/verses/rza/rza re1.mp3','stream'),
        make_audio('/verses/rza/rza re2.mp3','stream'),
        make_audio('/verses/rza/rza re3.mp3','stream'),
        make_audio('/verses/rza/rza re4.mp3','stream'),
        make_audio('/verses/rza/rza re5.mp3','stream'),
        make_audio('/verses/rza/rza re6.mp3','stream'),
        make_audio('/verses/rza/rza re7.mp3','stream'),
        make_audio('/verses/rza/rza re8.mp3','stream'),
        make_audio('/verses/rza/rza re9.mp3','stream'),
        make_audio('/verses/rza/rza tri1.mp3','stream'),
        make_audio('/verses/rza/rza tri2.mp3','stream'),
        make_audio('/verses/rza/rza jump1.mp3','stream'),
        make_audio('/verses/rza/rza jump2.mp3','stream'),
        make_audio('/verses/rza/rza jump3.mp3','stream'),
        make_audio('/verses/rza/rza jump4.mp3','stream'),
        make_audio('/verses/rza/rza neck1.mp3','stream'),
        make_audio('/verses/rza/rza neck2.mp3','stream'),
        make_audio('/verses/rza/rza neck3.mp3','stream'),
        make_audio('/verses/rza/rza neck4.mp3','stream'),
        make_audio('/verses/rza/rza neck5.mp3','stream')
    },
    ["U-God"] = {
        make_audio('/verses/u-god/ug tri1.mp3','stream'),
        make_audio('/verses/u-god/ug tri2.mp3','stream'),
        make_audio('/verses/u-god/ug tri3.mp3','stream'),
        make_audio('/verses/u-god/ug tri4.mp3','stream'),
        make_audio('/verses/u-god/ug tri5.mp3','stream'),
        make_audio('/verses/u-god/ug tri6.mp3','stream'),
        make_audio('/verses/u-god/ug tri7.mp3','stream'),
        make_audio('/verses/u-god/ug tri8.mp3','stream'),
        make_audio('/verses/u-god/ug chess1.mp3','stream'),
        make_audio('/verses/u-god/ug chess2.mp3','stream'),
        make_audio('/verses/u-god/ug chess3.mp3','stream'),
        make_audio('/verses/u-god/ug chess4.mp3','stream'),
        make_audio('/verses/u-god/ug gravel1.mp3','stream'),
        make_audio('/verses/u-god/ug gravel2.mp3','stream'),
        make_audio('/verses/u-god/ug gravel3.mp3','stream'),
        make_audio('/verses/u-god/ug gravel4.mp3','stream'),
        make_audio('/verses/u-god/ug gravel5.mp3','stream'),
        make_audio('/verses/u-god/ug gravel6.mp3','stream'),
        make_audio('/verses/u-god/ug gravel7.mp3','stream'),
        make_audio('/verses/u-god/ug jump1.mp3','stream'),
        make_audio('/verses/u-god/ug jump2.mp3','stream'),
        make_audio('/verses/u-god/ug jump3.mp3','stream'),
        make_audio('/verses/u-god/ug jump4.mp3','stream'),
        make_audio('/verses/u-god/ug neck1.mp3','stream'),
        make_audio('/verses/u-god/ug neck2.mp3','stream')
    },
    ["David Lee Roth"] = {
        make_audio('/verses/david_lee_roth/1.mp3', 'stream'), make_audio('/verses/david_lee_roth/2.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/3.mp3', 'stream'), make_audio('/verses/david_lee_roth/4.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/5.mp3', 'stream'), make_audio('/verses/david_lee_roth/6.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/7.mp3', 'stream'), make_audio('/verses/david_lee_roth/8.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/9.mp3', 'stream'), make_audio('/verses/david_lee_roth/10.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/11.mp3', 'stream'), make_audio('/verses/david_lee_roth/12.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/13.mp3', 'stream'), make_audio('/verses/david_lee_roth/14.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/15.mp3', 'stream'), make_audio('/verses/david_lee_roth/16.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/17.mp3', 'stream'), make_audio('/verses/david_lee_roth/18.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/19.mp3', 'stream'), make_audio('/verses/david_lee_roth/20.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/21.mp3', 'stream'), make_audio('/verses/david_lee_roth/22.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/23.mp3', 'stream'), make_audio('/verses/david_lee_roth/24.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/25.mp3', 'stream'), make_audio('/verses/david_lee_roth/26.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/27.mp3', 'stream'), make_audio('/verses/david_lee_roth/28.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/29.mp3', 'stream'), make_audio('/verses/david_lee_roth/30.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/31.mp3', 'stream'), make_audio('/verses/david_lee_roth/32.mp3', 'stream'),
        make_audio('/verses/david_lee_roth/33.mp3', 'stream')
    },
    ["Paul Stanley"] = {
        make_audio('/verses/paul_stanley/1.mp3', 'stream'), make_audio('/verses/paul_stanley/2.mp3', 'stream'),
        make_audio('/verses/paul_stanley/3.mp3', 'stream'), make_audio('/verses/paul_stanley/4.mp3', 'stream'),
        make_audio('/verses/paul_stanley/5.mp3', 'stream'), make_audio('/verses/paul_stanley/6.mp3', 'stream'),
        make_audio('/verses/paul_stanley/7.mp3', 'stream'), make_audio('/verses/paul_stanley/8.mp3', 'stream'),
        make_audio('/verses/paul_stanley/9.mp3', 'stream'), make_audio('/verses/paul_stanley/10.mp3', 'stream'),
        make_audio('/verses/paul_stanley/11.mp3', 'stream'), make_audio('/verses/paul_stanley/12.mp3', 'stream'),
        make_audio('/verses/paul_stanley/13.mp3', 'stream'), make_audio('/verses/paul_stanley/14.mp3', 'stream'),
        make_audio('/verses/paul_stanley/15.mp3', 'stream'), make_audio('/verses/paul_stanley/16.mp3', 'stream'),
        make_audio('/verses/paul_stanley/17.mp3', 'stream'), make_audio('/verses/paul_stanley/18.mp3', 'stream'),
        make_audio('/verses/paul_stanley/19.mp3', 'stream'), make_audio('/verses/paul_stanley/20.mp3', 'stream'),
        make_audio('/verses/paul_stanley/21.mp3', 'stream'), make_audio('/verses/paul_stanley/22.mp3', 'stream'),
        make_audio('/verses/paul_stanley/23.mp3', 'stream'), make_audio('/verses/paul_stanley/24.mp3', 'stream'),
        make_audio('/verses/paul_stanley/25.mp3', 'stream'), make_audio('/verses/paul_stanley/26.mp3', 'stream'),
        make_audio('/verses/paul_stanley/27.mp3', 'stream'), make_audio('/verses/paul_stanley/28.mp3', 'stream'),
        make_audio('/verses/paul_stanley/29.mp3', 'stream'), make_audio('/verses/paul_stanley/30.mp3', 'stream'),
        make_audio('/verses/paul_stanley/31.mp3', 'stream'), make_audio('/verses/paul_stanley/32.mp3', 'stream'),
        make_audio('/verses/paul_stanley/33.mp3', 'stream'), make_audio('/verses/paul_stanley/34.mp3', 'stream'),
        make_audio('/verses/paul_stanley/35.mp3', 'stream'), make_audio('/verses/paul_stanley/36.mp3', 'stream'),
        make_audio('/verses/paul_stanley/37.mp3', 'stream'), make_audio('/verses/paul_stanley/38.mp3', 'stream'),
        make_audio('/verses/paul_stanley/39.mp3', 'stream'), make_audio('/verses/paul_stanley/40.mp3', 'stream'),
        make_audio('/verses/paul_stanley/41.mp3', 'stream'), make_audio('/verses/paul_stanley/42.mp3', 'stream'),
        make_audio('/verses/paul_stanley/43.mp3', 'stream'), make_audio('/verses/paul_stanley/44.mp3', 'stream'),
        make_audio('/verses/paul_stanley/45.mp3', 'stream'), make_audio('/verses/paul_stanley/46.mp3', 'stream'),
        make_audio('/verses/paul_stanley/47.mp3', 'stream'), make_audio('/verses/paul_stanley/48.mp3', 'stream'),
        make_audio('/verses/paul_stanley/49.mp3', 'stream'), make_audio('/verses/paul_stanley/50.mp3', 'stream'),
        make_audio('/verses/paul_stanley/51.mp3', 'stream'), make_audio('/verses/paul_stanley/52.mp3', 'stream'),
        make_audio('/verses/paul_stanley/53.mp3', 'stream'), make_audio('/verses/paul_stanley/54.mp3', 'stream'),
        make_audio('/verses/paul_stanley/55.mp3', 'stream'), make_audio('/verses/paul_stanley/56.mp3', 'stream'),
        make_audio('/verses/paul_stanley/57.mp3', 'stream'), make_audio('/verses/paul_stanley/58.mp3', 'stream'),
        make_audio('/verses/paul_stanley/59.mp3', 'stream'), make_audio('/verses/paul_stanley/60.mp3', 'stream'),
        make_audio('/verses/paul_stanley/61.mp3', 'stream'), make_audio('/verses/paul_stanley/62.mp3', 'stream'),
        make_audio('/verses/paul_stanley/63.mp3', 'stream'), make_audio('/verses/paul_stanley/64.mp3', 'stream'),
        make_audio('/verses/paul_stanley/65.mp3', 'stream'), make_audio('/verses/paul_stanley/66.mp3', 'stream'),
        make_audio('/verses/paul_stanley/67.mp3', 'stream'), make_audio('/verses/paul_stanley/68.mp3', 'stream'),
        make_audio('/verses/paul_stanley/69.mp3', 'stream'), make_audio('/verses/paul_stanley/70.mp3', 'stream'),
        make_audio('/verses/paul_stanley/71.mp3', 'stream'), make_audio('/verses/paul_stanley/72.mp3', 'stream'),
        make_audio('/verses/paul_stanley/73.mp3', 'stream'), make_audio('/verses/paul_stanley/74.mp3', 'stream'),
        make_audio('/verses/paul_stanley/75.mp3', 'stream'), make_audio('/verses/paul_stanley/76.mp3', 'stream'),
        make_audio('/verses/paul_stanley/77.mp3', 'stream'), make_audio('/verses/paul_stanley/78.mp3', 'stream'),
        make_audio('/verses/paul_stanley/79.mp3', 'stream'), make_audio('/verses/paul_stanley/80.mp3', 'stream'),
        make_audio('/verses/paul_stanley/81.mp3', 'stream'), make_audio('/verses/paul_stanley/82.mp3', 'stream'),
        make_audio('/verses/paul_stanley/83.mp3', 'stream'), make_audio('/verses/paul_stanley/84.mp3', 'stream'),
        make_audio('/verses/paul_stanley/85.mp3', 'stream'), make_audio('/verses/paul_stanley/86.mp3', 'stream'),
        make_audio('/verses/paul_stanley/87.mp3', 'stream'), make_audio('/verses/paul_stanley/88.mp3', 'stream'),
        make_audio('/verses/paul_stanley/89.mp3', 'stream'), make_audio('/verses/paul_stanley/90.mp3', 'stream'),
        make_audio('/verses/paul_stanley/91.mp3', 'stream'), make_audio('/verses/paul_stanley/92.mp3', 'stream'),
        make_audio('/verses/paul_stanley/93.mp3', 'stream'), make_audio('/verses/paul_stanley/94.mp3', 'stream'),
        make_audio('/verses/paul_stanley/95.mp3', 'stream'), make_audio('/verses/paul_stanley/96.mp3', 'stream')
    }
}

function setup_audio(name)
    return VERSES[name]
end