function setupAudio(name)
        if name == 'Cappadonna' then
            return {
            love.audio.newSource('/verses/Cappadonna/cap tri1.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri2.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri3.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri4.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri5.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri6.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap tri7.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap jump1.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap jump2.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap jump3.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap jump4.mp3','stream'),
            love.audio.newSource('/verses/Cappadonna/cap jump5.mp3','stream')
        }
        elseif name == 'Ghostface Killah' then
                return {
            love.audio.newSource('/verses/Ghostface/gf chess1.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess2.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess3.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess4.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess5.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess6.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf chess7.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri1.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri2.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri3.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri4.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri5.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri6.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf tri7.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf gravel1.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf gravel2.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf gravel3.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf gravel4.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf gravel5.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf jump1.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf jump2.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf jump3.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf jump4.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf jump5.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf neck1.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf neck2.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf neck3.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf neck4.mp3','stream'),
            love.audio.newSource('/verses/Ghostface/gf neck5.mp3','stream')
        }
        elseif name == 'GZA' then
                return {
            love.audio.newSource('/verses/GZA/gza re1.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re2.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re3.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re4.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re5.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re6.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re7.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza re8.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza tri1.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza tri2.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza tri3.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza jump1.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza jump2.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza jump3.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza jump4.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck1.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck2.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck3.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck4.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck5.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck6.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck7.mp3','stream'),
            love.audio.newSource('/verses/GZA/gza neck8.mp3','stream')
        }
        elseif name == 'Inspectah Deck' then
                return {
            love.audio.newSource('/verses/Inspectah Deck/deck tri1.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri2.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri3.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri4.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri5.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri6.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri7.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri8.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck tri9.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess1.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess2.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess3.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess4.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess5.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck chess6.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck jump1.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck jump2.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck neck1.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck neck2.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck neck3.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck neck4.mp3','stream'),
            love.audio.newSource('/verses/Inspectah Deck/deck neck5.mp3','stream')
        }
        elseif name == 'Masta Killa' then
                return {
            love.audio.newSource('/verses/Masta Killa/mk tri1.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk tri2.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk tri3.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk tri4.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk tri5.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk tri6.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess1.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess2.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess3.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess4.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess5.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess6.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk chess7.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk jump1.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk jump2.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk jump3.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob1.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob2.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob3.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob4.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob5.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob6.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob7.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob8.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob9.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob10.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob11.mp3','stream'),
            love.audio.newSource('/verses/Masta Killa/mk ob12.mp3','stream')

        }
        elseif name == 'Method Man' then
                return {
            love.audio.newSource('/verses/Method Man/meth tri1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri4.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri5.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri6.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri7.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth tri8.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re4.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re5.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re6.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth re7.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel4.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel5.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel6.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel7.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel8.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel9.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel10.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth gravel11.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump4.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump5.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth jump6.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck4.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck5.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth neck6.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth shame1.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth shame2.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth shame3.mp3','stream'),
            love.audio.newSource('/verses/Method Man/meth shame4.mp3','stream')
        }
        elseif name == "Ol' Dirty Bastard" then
                return {
            love.audio.newSource('/verses/ODB/odb chess1.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess2.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess3.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess4.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess5.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess6.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess7.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess8.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess9.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb chess10.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb re1.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb neck1.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb neck2.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb neck3.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb neck4.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame1.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame2.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame3.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame4.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame5.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame6.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame7.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame8.mp3','stream'),
            love.audio.newSource('/verses/ODB/odb shame9.mp3','stream')
        }
        elseif name == 'Raekwon' then
                return {
            love.audio.newSource('/verses/Raekwon/rae tri1.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae tri2.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae tri3.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae tri4.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae tri5.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess1.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess2.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess3.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess4.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess5.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae chess6.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae jump1.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae jump2.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae jump3.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae jump4.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae jump5.mp3','stream'),           
            love.audio.newSource('/verses/Raekwon/rae neck1.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae neck2.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae neck3.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae neck4.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae neck5.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae shame1.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae shame2.mp3','stream'),
            love.audio.newSource('/verses/Raekwon/rae shame3.mp3','stream')
        }
        elseif name == 'RZA' then
                return {
            love.audio.newSource('/verses/RZA/rza re1.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re2.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re3.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re4.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re5.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re6.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re7.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re8.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza re9.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza tri1.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza tri2.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza jump1.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza jump2.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza jump3.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza jump4.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza neck1.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza neck2.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza neck3.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza neck4.mp3','stream'),
            love.audio.newSource('/verses/RZA/rza neck5.mp3','stream')
        }
        elseif name == 'U-God' then
                return {
            love.audio.newSource('/verses/U-God/ug tri1.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri2.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri3.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri4.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri5.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri6.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri7.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug tri8.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug chess1.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug chess2.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug chess3.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug chess4.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel1.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel2.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel3.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel4.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel5.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel6.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug gravel7.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug jump1.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug jump2.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug jump3.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug jump4.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug neck1.mp3','stream'),
            love.audio.newSource('/verses/U-God/ug neck2.mp3','stream')
        }
        elseif name == 'David Lee Roth' then
                return {
        love.audio.newSource('/verses/David Lee Roth/1.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/2.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/3.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/4.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/5.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/6.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/7.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/8.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/9.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/10.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/11.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/12.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/13.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/14.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/15.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/16.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/17.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/18.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/19.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/20.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/21.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/22.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/23.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/24.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/25.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/26.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/27.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/28.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/29.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/30.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/31.mp3', 'stream'), love.audio.newSource('/verses/David Lee Roth/32.mp3', 'stream'),
        love.audio.newSource('/verses/David Lee Roth/33.mp3', 'stream')
        }
        elseif name == 'Paul Stanley' then
                return {
        love.audio.newSource('/verses/Paul Stanley/1.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/2.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/3.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/4.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/5.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/6.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/7.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/8.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/9.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/10.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/11.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/12.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/13.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/14.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/15.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/16.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/17.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/18.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/19.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/20.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/21.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/22.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/23.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/24.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/25.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/26.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/27.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/28.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/29.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/30.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/31.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/32.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/33.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/34.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/35.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/36.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/37.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/38.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/39.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/40.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/41.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/42.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/43.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/44.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/45.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/46.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/47.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/48.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/49.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/50.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/51.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/52.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/53.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/54.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/55.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/56.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/57.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/58.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/59.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/60.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/61.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/62.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/63.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/64.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/65.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/66.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/67.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/68.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/69.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/70.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/71.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/72.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/73.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/74.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/75.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/76.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/77.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/78.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/79.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/80.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/81.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/82.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/83.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/84.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/85.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/86.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/87.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/88.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/89.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/90.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/91.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/92.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/93.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/94.mp3', 'stream'),
        love.audio.newSource('/verses/Paul Stanley/95.mp3', 'stream'), love.audio.newSource('/verses/Paul Stanley/96.mp3', 'stream')
        }
        end
end